version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_springboot2
    environment:
      MYSQL_ROOT_PASSWORD: nasa
    ports:
      - "3307:3306"
    volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
