
server:
  error:
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: nasa
  jpa:
    hibernate:
      ddl-auto: update
